### PR TITLE
Post-install Configuration Guide needed

### PR DESCRIPTION
**Pull request by anthonygtellez**
Pull Request comprises of two sample files with proposed methods for Data Model Optimization, Enforcing Role Based Access Controls for searches, Volume Retention, Utilizing a custom index for Wildfire Report storage. 
1. Data models are searching all non-internal indexes to locate pan logs. This can be optimized by specifying the index they have been stored in increasing the efficiently.

2/4. RBACs - Wildfire data is collected into index=main, however many customers do not realize this and may not want these reports searchable by all users who inherit that index by default. Secondly, the dashboards are relying on the role of the user to deny them from searching palo-alto data, but because index=main is specified in the savedsearches.conf all users will be able see this data in some of the dashboards. 
1. Many customers use volume sizing to set retention periods on how quickly to roll the data to frozen or retain for compliance reasons. Splunk PS regularly sets these configurations differently based on daily volume per source and hardware capacity. index=main is rarely used and may have a retention is set shorter than the palo-alto index used by the customer.

I have added comments to the configurations for review or further discussion. I have added them in the /local folder so they can be tested. The lines will need to be uncommented in both macros.conf.custom & savedsearches.conf.custom.

### CODE REVIEW

**Comment by btorresgil** [comment]
Hi Anthony, thanks for the pull request.  I like your approach using sample files that can be deployed when needed.  Unfortunately Splunk no longer allows apps to have a 'local' directory, but that is easily changed.  I'll make sure this gets integrated in the next release.

Thanks again!
 -Brian

**Comment by anthonygtellez** [comment]
That's perfectly fine. I tossed them in local for testing and validation purposes. When shipping via splunkbase they should go into /default as best practice.

**Comment by btorresgil** [comment]
Lets handle this in a post-install configuration guide.  This an other customizations are important for post-install, but might not apply to all customers.  No changes to app or add-on, but make a documentation change.

**Comment by btorresgil** [comment]
Working on a documentation overhaul that will resolve this issue.  Stay tuned.

**Comment by darizotas** [comment]
Hi @btorresgil , any update on this? I followed what @anthonygtellez recommended in his pull request and it works. Not sure if completely as the app has evolve.

**Comment by btorresgil** [comment]
Closing this PR, added new documentation site with new information on configuration.

**Pull request closed without merging**
