### PR TITLE
Added extractions & sourcetyping for pan:correlation events

### PR DESCRIPTION
**Pull request by niemesrw**
I modified props.conf & transforms.conf and tried to follow the existing methodology to change sourcetype and extract fields.  I also made it CIM compatible by creating an eventtype called pan_correlation and tagging it appropriately.  There might be some datamodel work that I didn't get a chance to look into, and I didn't create or modify any dashboards.  This doesn't capture all of the correlation event information since they aren't being logged fully as far as I can tell.  I'll look into using the API to pull the events as a next step.

### CODE REVIEW

**Comment by btorresgil** [comment]
Thanks for the pull request.  Unfortunately the correlation log format is not finalized and is planned to change in a future version of PAN-OS.  We'll be supporting it after that change is released very soon.  We'll merge your pull request at that time and then make the changes needed for the finalized log format.  Thanks again!

**Comment by ymylei** [comment]
Any updates on this pull request / request in general? 

The correlation events have been appearing the logs from the PAN devices for a while now, but I haven't seen any developments related to this nor any documentation from PA on the syslog formatting of these events.

**Comment by btorresgil** [comment]
Hello, thanks for checking in.  Support is added in Add-on 3.8.1 which is submitted to Splunk and awaiting approval for release.  We will also add some further enhancements in 3.8.2 which will come after that.

**Comment by ymylei** [comment]
Thanks for the update!

**Pull request closed without merging**
